apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yfsoftcom/gotest:1.3.3
        env:
          - name: REDIS_HOST
            value: "192.168.39.169"
          - name: REDIS_PORT
            value: "31311"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
