apiVersion: v1
kind: Pod
metadata:
  name: gotest
  labels:
    name: gotest
    type: demo-foo
spec:
  containers:
    - name: gotest 
      image: yfsoftcom/gotest:1.3.3
      env:
        - name: REDIS_HOST
          value: "172.17.0.3"
        - name: REDIS_PORT
          value: "6379"
      ports:
        - containerPort: 8080